### ISSUE TITLE
Từ Syscon của Coccoc

### ISSUE THREAD

**Issue by hoangdh** [bienkma/bigdata#1]
Với kiến thức như thế này thì có được chiêu mộ không ạ?
https://github.com/hoangdh/bigdata-notes

**Comment by bienkma** [comment]
@hoangdh cho anh email của em hoặc liên hệ với anh qua bientd88@gmail.com nhé. Anh em setup 1 buổi cf.

**Comment by hoangdh** [comment]
E gửi thông tin Tele ạ: https://t.me/hoangdh
